### ISSUE TITLE
Revisar que existan (sino crear) las pantallas comprometidas para la entrega 2

### ISSUE THREAD

**Issue by BaPablo** [ManuelEV/iRecycler-Mobile#4]

**Comment by ManuelEV** [comment]
Según los mockups que presentamos, estarían listas las pantallas del mapa general y la de agregar punto. La que falta es la de los gráficos de la capacidad por cada punto de reciclaje

**Comment by BaPablo** [comment]
@ManuelEV se cierra entonces!
